// Package store defines core data types and the Store interface.
// Concrete SQLite implementation lives in internal/store/sqlite (or next to this file).
package store

import "time"

// Domain represents a news domain (e.g. "ai", "web3", "biotech").
// Day 1 only instantiates "ai".
type Domain struct {
	ID         string // 'ai', 'web3', ...
	Name       string // display name
	ConfigPath string // config/{id}.yaml
	CreatedAt  time.Time
}

// Source represents a concrete data source configuration
// (e.g. "GitHub Trending daily", "smol.ai RSS feed", "Folo list NEWS_AGGREGATOR").
type Source struct {
	ID         int64
	DomainID   string
	Type       string // 'github_trending' | 'rss' | 'folo_list' | ...
	Name       string
	ConfigJSON string // type-specific config (feed URL, list ID, auth, ...)
	// Category is parsed from ConfigJSON (SourceConfig.Category) when the
	// row is loaded. It is one of: news, blog, paper, project, community.
	// Used by classify to pre-bucket items via a deterministic rule before
	// asking the LLM for second-pass disambiguation of news → product_update
	// vs industry. Not persisted as its own column — the authoritative copy
	// lives in config/ai.yaml and is re-parsed on every ListEnabledSources
	// call.
	Category   string
	Enabled    bool
	CreatedAt  time.Time
}

// RawItem is a single item ingested from a Source, before any LLM processing.
type RawItem struct {
	ID           int64
	DomainID     string
	SourceID     int64
	ExternalID   string    // source-side unique ID for dedup
	URL          string
	Title        string
	Author       string
	PublishedAt  time.Time // zero value allowed if unknown
	FetchedAt    time.Time
	Content      string // extracted body; may be empty on Day 1
	MetadataJSON string // arbitrary extra metadata
}

// Issue represents a single daily briefing (one per domain per date).
type Issue struct {
	ID           int64
	DomainID     string
	IssueDate    time.Time  // only YYYY-MM-DD portion is meaningful
	IssueNumber  int        // monotonic per-domain counter
	Title        string     // e.g. "2026年4月11日 AI洞察日报"
	Summary      string     // today's summary paragraph
	Status       string     // 'draft' | 'generated' | 'published'
	SourceCount  int        // number of sources consulted
	ItemCount    int        // number of issue items
	GeneratedAt  *time.Time // nil until generated
	PublishedAt  *time.Time // nil until published
}

// IssueItem is one entry within an Issue, grouped into a named section.
type IssueItem struct {
	ID              int64
	IssueID         int64
	Section         string // 'product_update' | 'research' | 'industry' | 'opensource' | 'social'
	Seq             int    // order within section (1-based)
	Title           string
	BodyMD          string
	SourceURLsJSON  string // JSON array of upstream URLs
	RawItemIDsJSON  string // JSON array of contributing raw_items.id
	CreatedAt       time.Time
}

// IssueInsight captures the cross-item "industry insight" and "our takeaways"
// generated by the LLM for an Issue.
type IssueInsight struct {
	ID          int64
	IssueID     int64
	IndustryMD  string  // 3-4 行业洞察 bullets (markdown)
	OurMD       string  // 2-3 对我们的启发 bullets (markdown)
	Model       string  // e.g. "gpt-5.4"
	Temperature float64
	RetryCount  int     // how many repair attempts were needed
	GeneratedAt time.Time
}

// WeeklyIssue represents a weekly summary report aggregating daily Issues.
type WeeklyIssue struct {
	ID            int64
	DomainID      string
	Year          int
	Week          int        // ISO 8601 week number
	StartDate     time.Time  // Monday
	EndDate       time.Time  // Sunday
	Title         string
	FocusMD       string     // 本周聚焦
	SignalsMD     string     // 信号与噪音
	TrendsMD       string     // 宏观趋势
	TrendsDiagram       string     // Mermaid simple diagram for trends
	TrendsDiagramDetail string     // Mermaid detailed diagram for trends
	TakeawaysMD         string     // 对我们的启发
	PonderMD      string     // 本周思考
	FullMD        string     // rendered full markdown
	DailyIssueIDs string     // JSON array of daily issue IDs
	Status        string
	GeneratedAt   *time.Time
	PublishedAt   *time.Time
}

// Delivery records an attempt to publish an Issue to a specific channel.
type Delivery struct {
	ID           int64
	IssueID      int64
	Channel      string // 'slack_test' | 'slack_prod' | 'feishu_doc' | 'feishu_bot'
	Target       string // webhook URL / doc token / chat_id
	Status       string // 'sent' | 'failed' | 'skipped'
	ResponseJSON string // raw response body or error message
	SentAt       time.Time
}

// Section name constants used by compose/render to categorize items.
const (
	SectionProductUpdate = "product_update"
	SectionResearch      = "research"
	SectionIndustry      = "industry"
	SectionOpenSource    = "opensource"
	SectionSocial        = "social"
)

// Issue status constants.
const (
	IssueStatusDraft     = "draft"
	IssueStatusGenerated = "generated"
	IssueStatusPublished = "published"
)

// Delivery status constants.
const (
	DeliveryStatusSent    = "sent"
	DeliveryStatusFailed  = "failed"
	DeliveryStatusSkipped = "skipped"
)

// Channel name constants.
const (
	ChannelSlackTest = "slack_test"
	ChannelSlackProd = "slack_prod"
	ChannelFeishuDoc = "feishu_doc"
	ChannelFeishuBot = "feishu_bot"
)
